/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.aires.app;

import br.com.aires.dal.LoteamentoIterator;
import br.com.aires.dal.PlainadoraDalAdapter;
import br.com.aires.dal.PlainadoraNewHollandDal;
import br.com.aires.interfaces.Interface_Iterator;
import br.com.aires.interfaces.Interface_Terraplanagem;
import br.com.aires.model.Loteamento;
import javax.swing.JOptionPane;

/**
 *
 *
 */
public class LoteamentoPlainadoApp extends javax.swing.JFrame {

    //Referenciação dos objetos
    private Loteamento loteamento;
    private Interface_Terraplanagem objeto;
    private Loteamento[] lotes;
    private Interface_Iterator loteamIterator;
    private int tamanho;

    /**
     * Creates new form LoteamentoPlainado
     */
    public LoteamentoPlainadoApp() {
        initComponents();

        // Inicialização dos objetos, variáveis e componentes necessários nesta
        tamanho = 3;
        jTextAreaSaida.setLineWrap(true);

        // Preenchimento do combBox com as opções de execução do botão
        jComboBoxOpçoesDePlainar.removeAllItems();
        String[] opcoes = {" ", "NEW HOLLAND", "JHON DEERE"};
        for (String plaina : opcoes) {
            jComboBoxOpçoesDePlainar.addItem(plaina);
        }

        preencherCampos();
    }

    private void limpaCampos() {
        jTextFieldNomeDoLoteamento.setText("");
        jTextFieldNomeDoBairro.setText("");
        jTextFieldMetrosQuadrados.setText("");
        jTextFieldNomeDoLoteamento.requestFocus();
    }

    // Preencher campos para testes iniciais
    private void preencherCampos() {
        jTextFieldNomeDoLoteamento.setText("São Paulo");
        jTextFieldNomeDoBairro.setText("Paulista");
        jTextFieldMetrosQuadrados.setText("10000");
        jComboBoxOpçoesDePlainar.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLoteamentoPlainado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomeDoLoteamento = new javax.swing.JTextField();
        jTextFieldNomeDoBairro = new javax.swing.JTextField();
        jTextFieldMetrosQuadrados = new javax.swing.JTextField();
        jButtonPlainadora_Dal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSaida = new javax.swing.JTextArea();
        jComboBoxOpçoesDePlainar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loteamento Plainado");
        setFont(new java.awt.Font("Agency FB", 0, 13)); // NOI18N
        setResizable(false);

        jPanelLoteamentoPlainado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel1.setText("Nome do Loteamento:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel2.setText("Nome do Bairro:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel3.setText("Quant. de Metros Quadrados do Loteamento:");

        jTextFieldNomeDoLoteamento.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N

        jTextFieldNomeDoBairro.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N

        jTextFieldMetrosQuadrados.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N

        jButtonPlainadora_Dal.setText("Plainadora New Holland");
        jButtonPlainadora_Dal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlainadora_DalActionPerformed(evt);
            }
        });

        jTextAreaSaida.setColumns(20);
        jTextAreaSaida.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSaida);

        jComboBoxOpçoesDePlainar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxOpçoesDePlainar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOpçoesDePlainarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel4.setText("Opções:");

        javax.swing.GroupLayout jPanelLoteamentoPlainadoLayout = new javax.swing.GroupLayout(jPanelLoteamentoPlainado);
        jPanelLoteamentoPlainado.setLayout(jPanelLoteamentoPlainadoLayout);
        jPanelLoteamentoPlainadoLayout.setHorizontalGroup(
            jPanelLoteamentoPlainadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoteamentoPlainadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLoteamentoPlainadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLoteamentoPlainadoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeDoLoteamento))
                    .addGroup(jPanelLoteamentoPlainadoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addComponent(jTextFieldNomeDoBairro))
                    .addGroup(jPanelLoteamentoPlainadoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMetrosQuadrados, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoteamentoPlainadoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxOpçoesDePlainar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPlainadora_Dal)))
                .addContainerGap())
        );
        jPanelLoteamentoPlainadoLayout.setVerticalGroup(
            jPanelLoteamentoPlainadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoteamentoPlainadoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelLoteamentoPlainadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNomeDoLoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLoteamentoPlainadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomeDoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLoteamentoPlainadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMetrosQuadrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLoteamentoPlainadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPlainadora_Dal)
                    .addComponent(jComboBoxOpçoesDePlainar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLoteamentoPlainado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLoteamentoPlainado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlainadora_DalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlainadora_DalActionPerformed
        // TODO add your handling code here:
        try {

            jTextAreaSaida.setText("");
            // Carregando valores nos atributos do objeto loteamento
            String nomeLoteamento = jTextFieldNomeDoLoteamento.getText();
            String nomeBairro = jTextFieldNomeDoBairro.getText();
            int metrosQuadrados = Integer.parseInt(jTextFieldMetrosQuadrados.getText());

            // instanciando o objeto loteamento e atribuindo valores às variáveis
            loteamento = new Loteamento(nomeLoteamento, nomeBairro, metrosQuadrados);

            // Instanciando o vetor lotes do tipo Loteamento
            lotes = new Loteamento[tamanho];

            // Armazenando um objeto do tipo loteamento na primeira posição do vetor 
            lotes[0] = new Loteamento(nomeLoteamento, nomeBairro, metrosQuadrados);

            /* Instanciando o objeto do tipo Iterator que recebe como parâmetro
             * um vetor de coleção de objetos do tipo loteamento
             */
            loteamIterator = new LoteamentoIterator(lotes);

            // Lendo o vetor de objetos através do Iterator que permite o acesso
            while (loteamIterator.hasNext()) {
                Loteamento lotes = (Loteamento) loteamIterator.next();
                // Imprimindo os dados do loteamento
                jTextAreaSaida.append(lotes.toString());
                jTextAreaSaida.append("----------------------------------------\n");
            }

            // Verificando qual botão está habilitado
            if (jButtonPlainadora_Dal.getLabel().equalsIgnoreCase("Plainar com New Holland")) {

                /* Instanciando um objeto do tipo da Interface_Terraplanagem
                 * com a classe PlainadoraNewHolland
                 */
                objeto = new PlainadoraNewHollandDal();

                // Imprimindo no textArea os dados da plainadora, e os valores do método da interface
                jTextAreaSaida.append(objeto.toString() + objeto.terraplainarComNewHolland(loteamento).toUpperCase());

            } else {

                /* Instanciando um objeto do tipo da Interface_Terraplanagem
                 * com a classe PlainadoraDalAdapter
                 */
                objeto = new PlainadoraDalAdapter();

                // Imprimindo no textArea os dados da plainadora, e os valores do método da interface
                jTextAreaSaida.append(objeto.terraplainarComNewHolland(loteamento).toUpperCase());

            }

            limpaCampos();

        } catch (Exception erro) {

            JOptionPane.showMessageDialog(null, "Atenção no botão Plaina" + erro.getMessage());

        }
    }//GEN-LAST:event_jButtonPlainadora_DalActionPerformed

    private void jComboBoxOpçoesDePlainarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOpçoesDePlainarActionPerformed
        // TODO add your handling code here:
        try {

            /* if condicional para escolha de qual plainadora
               Plainadora NewHolland que implementa a interface
               Ou plainadora Adapter que implementa a interface e
               instancia dentro dela um objeto do tipo da 
               plainadora John Deere 
             */
            int index = jComboBoxOpçoesDePlainar.getSelectedIndex();
            if (index == 0) {
                jButtonPlainadora_Dal.setLabel("Plainadora");
            } else if (index == 1) {
                jButtonPlainadora_Dal.setLabel("Plainar com New Holland");
            } else {
                jButtonPlainadora_Dal.setLabel("Plainar com John Deere");
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Atenção no combBox opções de plainadora\n" + erro.getMessage());
        }

    }//GEN-LAST:event_jComboBoxOpçoesDePlainarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoteamentoPlainadoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoteamentoPlainadoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoteamentoPlainadoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoteamentoPlainadoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoteamentoPlainadoApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPlainadora_Dal;
    private javax.swing.JComboBox<String> jComboBoxOpçoesDePlainar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelLoteamentoPlainado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSaida;
    private javax.swing.JTextField jTextFieldMetrosQuadrados;
    private javax.swing.JTextField jTextFieldNomeDoBairro;
    private javax.swing.JTextField jTextFieldNomeDoLoteamento;
    // End of variables declaration//GEN-END:variables
}
